apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev1-nfs-claim
  namespace: dev-1
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
